-- AlterTable
ALTER TABLE "Usuario" ADD COLUMN     "cicloDuracionDias" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "cicloInicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "presupuestoMensual" DOUBLE PRECISION NOT NULL DEFAULT 0;
